//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RC.EduCloud.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bangongcheliangshiyongjilu
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> CLID { get; set; }
        public string MDD { get; set; }
        public Nullable<decimal> LCS { get; set; }
        public Nullable<System.DateTime> CCSJ { get; set; }
        public Nullable<System.DateTime> HCSJ { get; set; }
        public string CCLY { get; set; }
        public string BZ { get; set; }
        public Nullable<System.Guid> SJID { get; set; }
        public Nullable<System.Guid> SQRID { get; set; }
        public Nullable<System.DateTime> SQSJ { get; set; }
        public Nullable<int> CLSYZT { get; set; }
        public Nullable<System.Guid> SHRID { get; set; }
        public Nullable<System.DateTime> SHSJ { get; set; }
        public string SHBTGYY { get; set; }
        public Nullable<System.Guid> QXRID { get; set; }
        public Nullable<System.DateTime> QXSJ { get; set; }
        public string QXYY { get; set; }
        public Nullable<System.Guid> JLCJR { get; set; }
        public Nullable<System.DateTime> JLCJSJ { get; set; }
        public Nullable<System.Guid> JLXGR { get; set; }
        public Nullable<System.DateTime> JLXGSJ { get; set; }
        public Nullable<bool> JLSFYX { get; set; }
    }
}
